# --- Builder ---
FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o etl ./cmd/etl/main.go

# --- Runtime ---
FROM alpine:3.20

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/etl .
COPY --from=builder /app/data ./data

CMD ["./etl"]
